### ISSUE TITLE
Some of tags are missing

### ISSUE THREAD

**Issue by inf1nite-lo0p** [justinmahar/react-html-props#1]
Hi! Thanks for these amazing TS type definitions which save me a ton of time :)

I realized some of the tags are missing such as `<header>` , `<time>` , `<footer>` or maybe some other which I haven't come across yet. Im currently using  `ElementProps` for them. I can do a pull request and add them if you want.

**Comment by justinmahar** [comment]
Added all missing tags listed by [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/abbr)
