### ISSUE TITLE
Support for React 18

### ISSUE THREAD

**Issue by ChristoRibeiro** [justinmahar/react-html-props#2]
Does it work with react 18 @justinmahar?

**Comment by justinmahar** [comment]
Hey, thanks for the heads up on React 18. It should! I will push out a patch tonight that takes care of this.

**Comment by justinmahar** [comment]
All set. Give it a shot and close if it's fixed for you.

**Comment by ChristoRibeiro** [comment]
All is good! Thanks for the quick support 👍
